server:
  servlet:
    context-path: /inventory-service
  port: 8082

spring:
  zipkin:
    base-url: http://192.168.0.101:9411/
  sleuth:
    sampler:
      probability: 1.0
  application:
    name: inventory-service
  datasource:
    url: jdbc:mysql://192.168.0.102:3306/microservices
    username: sandeep
    password: sandeep
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
#----------------below logging will activate the jpa transactional log
#actuator endpoint managemnet
management:
  endpoint:
    shutdown:
      enabled: true
    beans:
      enabled: true
    env:
      enabled: true
    web:
      exposure:
        include:  true
        exclude: threaddump



eureka:
  instance:
    # Necessary for Docker as it doesn't have DNS entries
    prefer-ip-address: true
    # Necessary for Docker otherwise you will get 172.0.0.x IP
    ip-address: 192.168.0.102
  #"${HOST}"
  client:
    serviceUrl:
      # Location of your eureka server
      defaultZone: http://192.168.0.101:8761/eureka/

# Zipkin configuration





  #file:


    #org.springframework.orm.jpa: DEBUG
    #org.springframework.transaction: DEBUG

  #pattern:
   # console: %d{dd-MM-yyyy HH:mm:ss.SSS} %magenta([%thread]) %highlight(%-5level) %logger.%M - %msg%n
